package com.lantian.FindCar.dao;

import java.util.Date;

public class ConfirmCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confirm_code.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confirm_code.phonenum
     *
     * @mbggenerated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confirm_code.confirmCode
     *
     * @mbggenerated
     */
    private String confirmcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confirm_code.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_code.id
     *
     * @return the value of confirm_code.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_code.id
     *
     * @param id the value for confirm_code.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_code.phonenum
     *
     * @return the value of confirm_code.phonenum
     *
     * @mbggenerated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_code.phonenum
     *
     * @param phonenum the value for confirm_code.phonenum
     *
     * @mbggenerated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_code.confirmCode
     *
     * @return the value of confirm_code.confirmCode
     *
     * @mbggenerated
     */
    public String getConfirmcode() {
        return confirmcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_code.confirmCode
     *
     * @param confirmcode the value for confirm_code.confirmCode
     *
     * @mbggenerated
     */
    public void setConfirmcode(String confirmcode) {
        this.confirmcode = confirmcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_code.create_time
     *
     * @return the value of confirm_code.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_code.create_time
     *
     * @param createTime the value for confirm_code.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}