package com.lantian.FindCar.dao;

public class DriverAnimateInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_animate_information.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_animate_information.driver_base_id
     *
     * @mbggenerated
     */
    private Long driverBaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_animate_information.phonenum
     *
     * @mbggenerated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_animate_information.is_online
     *
     * @mbggenerated
     */
    private Integer isOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_animate_information.access_token
     *
     * @mbggenerated
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_animate_information.refresh_token
     *
     * @mbggenerated
     */
    private String refreshToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_animate_information.current_lat
     *
     * @mbggenerated
     */
    private Double currentLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_animate_information.current_lng
     *
     * @mbggenerated
     */
    private Double currentLng;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_animate_information.id
     *
     * @return the value of driver_animate_information.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_animate_information.id
     *
     * @param id the value for driver_animate_information.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_animate_information.driver_base_id
     *
     * @return the value of driver_animate_information.driver_base_id
     *
     * @mbggenerated
     */
    public Long getDriverBaseId() {
        return driverBaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_animate_information.driver_base_id
     *
     * @param driverBaseId the value for driver_animate_information.driver_base_id
     *
     * @mbggenerated
     */
    public void setDriverBaseId(Long driverBaseId) {
        this.driverBaseId = driverBaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_animate_information.phonenum
     *
     * @return the value of driver_animate_information.phonenum
     *
     * @mbggenerated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_animate_information.phonenum
     *
     * @param phonenum the value for driver_animate_information.phonenum
     *
     * @mbggenerated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_animate_information.is_online
     *
     * @return the value of driver_animate_information.is_online
     *
     * @mbggenerated
     */
    public Integer getIsOnline() {
        return isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_animate_information.is_online
     *
     * @param isOnline the value for driver_animate_information.is_online
     *
     * @mbggenerated
     */
    public void setIsOnline(Integer isOnline) {
        this.isOnline = isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_animate_information.access_token
     *
     * @return the value of driver_animate_information.access_token
     *
     * @mbggenerated
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_animate_information.access_token
     *
     * @param accessToken the value for driver_animate_information.access_token
     *
     * @mbggenerated
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_animate_information.refresh_token
     *
     * @return the value of driver_animate_information.refresh_token
     *
     * @mbggenerated
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_animate_information.refresh_token
     *
     * @param refreshToken the value for driver_animate_information.refresh_token
     *
     * @mbggenerated
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_animate_information.current_lat
     *
     * @return the value of driver_animate_information.current_lat
     *
     * @mbggenerated
     */
    public Double getCurrentLat() {
        return currentLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_animate_information.current_lat
     *
     * @param currentLat the value for driver_animate_information.current_lat
     *
     * @mbggenerated
     */
    public void setCurrentLat(Double currentLat) {
        this.currentLat = currentLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_animate_information.current_lng
     *
     * @return the value of driver_animate_information.current_lng
     *
     * @mbggenerated
     */
    public Double getCurrentLng() {
        return currentLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_animate_information.current_lng
     *
     * @param currentLng the value for driver_animate_information.current_lng
     *
     * @mbggenerated
     */
    public void setCurrentLng(Double currentLng) {
        this.currentLng = currentLng;
    }
}