package com.lantian.FindCar.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_record
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_record
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_record
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;
    
    /** add by lantian,set pageCut**/
    protected long start;
    protected long limit;

    public long getStart() {
		return start;
	}

	public void setStart(long start) {
		this.start = start;
	}

	public long getLimit() {
		return limit;
	}

	public void setLimit(long limit) {
		this.limit = limit;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    public OrderRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_record
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserAnimateIdIsNull() {
            addCriterion("user_animate_id is null");
            return (Criteria) this;
        }

        public Criteria andUserAnimateIdIsNotNull() {
            addCriterion("user_animate_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserAnimateIdEqualTo(Long value) {
            addCriterion("user_animate_id =", value, "userAnimateId");
            return (Criteria) this;
        }

        public Criteria andUserAnimateIdNotEqualTo(Long value) {
            addCriterion("user_animate_id <>", value, "userAnimateId");
            return (Criteria) this;
        }

        public Criteria andUserAnimateIdGreaterThan(Long value) {
            addCriterion("user_animate_id >", value, "userAnimateId");
            return (Criteria) this;
        }

        public Criteria andUserAnimateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_animate_id >=", value, "userAnimateId");
            return (Criteria) this;
        }

        public Criteria andUserAnimateIdLessThan(Long value) {
            addCriterion("user_animate_id <", value, "userAnimateId");
            return (Criteria) this;
        }

        public Criteria andUserAnimateIdLessThanOrEqualTo(Long value) {
            addCriterion("user_animate_id <=", value, "userAnimateId");
            return (Criteria) this;
        }

        public Criteria andUserAnimateIdIn(List<Long> values) {
            addCriterion("user_animate_id in", values, "userAnimateId");
            return (Criteria) this;
        }

        public Criteria andUserAnimateIdNotIn(List<Long> values) {
            addCriterion("user_animate_id not in", values, "userAnimateId");
            return (Criteria) this;
        }

        public Criteria andUserAnimateIdBetween(Long value1, Long value2) {
            addCriterion("user_animate_id between", value1, value2, "userAnimateId");
            return (Criteria) this;
        }

        public Criteria andUserAnimateIdNotBetween(Long value1, Long value2) {
            addCriterion("user_animate_id not between", value1, value2, "userAnimateId");
            return (Criteria) this;
        }

        public Criteria andDriverAnimateIdIsNull() {
            addCriterion("driver_animate_id is null");
            return (Criteria) this;
        }

        public Criteria andDriverAnimateIdIsNotNull() {
            addCriterion("driver_animate_id is not null");
            return (Criteria) this;
        }

        public Criteria andDriverAnimateIdEqualTo(Long value) {
            addCriterion("driver_animate_id =", value, "driverAnimateId");
            return (Criteria) this;
        }

        public Criteria andDriverAnimateIdNotEqualTo(Long value) {
            addCriterion("driver_animate_id <>", value, "driverAnimateId");
            return (Criteria) this;
        }

        public Criteria andDriverAnimateIdGreaterThan(Long value) {
            addCriterion("driver_animate_id >", value, "driverAnimateId");
            return (Criteria) this;
        }

        public Criteria andDriverAnimateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("driver_animate_id >=", value, "driverAnimateId");
            return (Criteria) this;
        }

        public Criteria andDriverAnimateIdLessThan(Long value) {
            addCriterion("driver_animate_id <", value, "driverAnimateId");
            return (Criteria) this;
        }

        public Criteria andDriverAnimateIdLessThanOrEqualTo(Long value) {
            addCriterion("driver_animate_id <=", value, "driverAnimateId");
            return (Criteria) this;
        }

        public Criteria andDriverAnimateIdIn(List<Long> values) {
            addCriterion("driver_animate_id in", values, "driverAnimateId");
            return (Criteria) this;
        }

        public Criteria andDriverAnimateIdNotIn(List<Long> values) {
            addCriterion("driver_animate_id not in", values, "driverAnimateId");
            return (Criteria) this;
        }

        public Criteria andDriverAnimateIdBetween(Long value1, Long value2) {
            addCriterion("driver_animate_id between", value1, value2, "driverAnimateId");
            return (Criteria) this;
        }

        public Criteria andDriverAnimateIdNotBetween(Long value1, Long value2) {
            addCriterion("driver_animate_id not between", value1, value2, "driverAnimateId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCarCateIsNull() {
            addCriterion("car_cate is null");
            return (Criteria) this;
        }

        public Criteria andCarCateIsNotNull() {
            addCriterion("car_cate is not null");
            return (Criteria) this;
        }

        public Criteria andCarCateEqualTo(String value) {
            addCriterion("car_cate =", value, "carCate");
            return (Criteria) this;
        }

        public Criteria andCarCateNotEqualTo(String value) {
            addCriterion("car_cate <>", value, "carCate");
            return (Criteria) this;
        }

        public Criteria andCarCateGreaterThan(String value) {
            addCriterion("car_cate >", value, "carCate");
            return (Criteria) this;
        }

        public Criteria andCarCateGreaterThanOrEqualTo(String value) {
            addCriterion("car_cate >=", value, "carCate");
            return (Criteria) this;
        }

        public Criteria andCarCateLessThan(String value) {
            addCriterion("car_cate <", value, "carCate");
            return (Criteria) this;
        }

        public Criteria andCarCateLessThanOrEqualTo(String value) {
            addCriterion("car_cate <=", value, "carCate");
            return (Criteria) this;
        }

        public Criteria andCarCateLike(String value) {
            addCriterion("car_cate like", value, "carCate");
            return (Criteria) this;
        }

        public Criteria andCarCateNotLike(String value) {
            addCriterion("car_cate not like", value, "carCate");
            return (Criteria) this;
        }

        public Criteria andCarCateIn(List<String> values) {
            addCriterion("car_cate in", values, "carCate");
            return (Criteria) this;
        }

        public Criteria andCarCateNotIn(List<String> values) {
            addCriterion("car_cate not in", values, "carCate");
            return (Criteria) this;
        }

        public Criteria andCarCateBetween(String value1, String value2) {
            addCriterion("car_cate between", value1, value2, "carCate");
            return (Criteria) this;
        }

        public Criteria andCarCateNotBetween(String value1, String value2) {
            addCriterion("car_cate not between", value1, value2, "carCate");
            return (Criteria) this;
        }

        public Criteria andStartLocationNameIsNull() {
            addCriterion("start_location_name is null");
            return (Criteria) this;
        }

        public Criteria andStartLocationNameIsNotNull() {
            addCriterion("start_location_name is not null");
            return (Criteria) this;
        }

        public Criteria andStartLocationNameEqualTo(String value) {
            addCriterion("start_location_name =", value, "startLocationName");
            return (Criteria) this;
        }

        public Criteria andStartLocationNameNotEqualTo(String value) {
            addCriterion("start_location_name <>", value, "startLocationName");
            return (Criteria) this;
        }

        public Criteria andStartLocationNameGreaterThan(String value) {
            addCriterion("start_location_name >", value, "startLocationName");
            return (Criteria) this;
        }

        public Criteria andStartLocationNameGreaterThanOrEqualTo(String value) {
            addCriterion("start_location_name >=", value, "startLocationName");
            return (Criteria) this;
        }

        public Criteria andStartLocationNameLessThan(String value) {
            addCriterion("start_location_name <", value, "startLocationName");
            return (Criteria) this;
        }

        public Criteria andStartLocationNameLessThanOrEqualTo(String value) {
            addCriterion("start_location_name <=", value, "startLocationName");
            return (Criteria) this;
        }

        public Criteria andStartLocationNameLike(String value) {
            addCriterion("start_location_name like", value, "startLocationName");
            return (Criteria) this;
        }

        public Criteria andStartLocationNameNotLike(String value) {
            addCriterion("start_location_name not like", value, "startLocationName");
            return (Criteria) this;
        }

        public Criteria andStartLocationNameIn(List<String> values) {
            addCriterion("start_location_name in", values, "startLocationName");
            return (Criteria) this;
        }

        public Criteria andStartLocationNameNotIn(List<String> values) {
            addCriterion("start_location_name not in", values, "startLocationName");
            return (Criteria) this;
        }

        public Criteria andStartLocationNameBetween(String value1, String value2) {
            addCriterion("start_location_name between", value1, value2, "startLocationName");
            return (Criteria) this;
        }

        public Criteria andStartLocationNameNotBetween(String value1, String value2) {
            addCriterion("start_location_name not between", value1, value2, "startLocationName");
            return (Criteria) this;
        }

        public Criteria andStartLocationLatIsNull() {
            addCriterion("start_location_lat is null");
            return (Criteria) this;
        }

        public Criteria andStartLocationLatIsNotNull() {
            addCriterion("start_location_lat is not null");
            return (Criteria) this;
        }

        public Criteria andStartLocationLatEqualTo(Double value) {
            addCriterion("start_location_lat =", value, "startLocationLat");
            return (Criteria) this;
        }

        public Criteria andStartLocationLatNotEqualTo(Double value) {
            addCriterion("start_location_lat <>", value, "startLocationLat");
            return (Criteria) this;
        }

        public Criteria andStartLocationLatGreaterThan(Double value) {
            addCriterion("start_location_lat >", value, "startLocationLat");
            return (Criteria) this;
        }

        public Criteria andStartLocationLatGreaterThanOrEqualTo(Double value) {
            addCriterion("start_location_lat >=", value, "startLocationLat");
            return (Criteria) this;
        }

        public Criteria andStartLocationLatLessThan(Double value) {
            addCriterion("start_location_lat <", value, "startLocationLat");
            return (Criteria) this;
        }

        public Criteria andStartLocationLatLessThanOrEqualTo(Double value) {
            addCriterion("start_location_lat <=", value, "startLocationLat");
            return (Criteria) this;
        }

        public Criteria andStartLocationLatIn(List<Double> values) {
            addCriterion("start_location_lat in", values, "startLocationLat");
            return (Criteria) this;
        }

        public Criteria andStartLocationLatNotIn(List<Double> values) {
            addCriterion("start_location_lat not in", values, "startLocationLat");
            return (Criteria) this;
        }

        public Criteria andStartLocationLatBetween(Double value1, Double value2) {
            addCriterion("start_location_lat between", value1, value2, "startLocationLat");
            return (Criteria) this;
        }

        public Criteria andStartLocationLatNotBetween(Double value1, Double value2) {
            addCriterion("start_location_lat not between", value1, value2, "startLocationLat");
            return (Criteria) this;
        }

        public Criteria andStartLocationLngIsNull() {
            addCriterion("start_location_lng is null");
            return (Criteria) this;
        }

        public Criteria andStartLocationLngIsNotNull() {
            addCriterion("start_location_lng is not null");
            return (Criteria) this;
        }

        public Criteria andStartLocationLngEqualTo(Double value) {
            addCriterion("start_location_lng =", value, "startLocationLng");
            return (Criteria) this;
        }

        public Criteria andStartLocationLngNotEqualTo(Double value) {
            addCriterion("start_location_lng <>", value, "startLocationLng");
            return (Criteria) this;
        }

        public Criteria andStartLocationLngGreaterThan(Double value) {
            addCriterion("start_location_lng >", value, "startLocationLng");
            return (Criteria) this;
        }

        public Criteria andStartLocationLngGreaterThanOrEqualTo(Double value) {
            addCriterion("start_location_lng >=", value, "startLocationLng");
            return (Criteria) this;
        }

        public Criteria andStartLocationLngLessThan(Double value) {
            addCriterion("start_location_lng <", value, "startLocationLng");
            return (Criteria) this;
        }

        public Criteria andStartLocationLngLessThanOrEqualTo(Double value) {
            addCriterion("start_location_lng <=", value, "startLocationLng");
            return (Criteria) this;
        }

        public Criteria andStartLocationLngIn(List<Double> values) {
            addCriterion("start_location_lng in", values, "startLocationLng");
            return (Criteria) this;
        }

        public Criteria andStartLocationLngNotIn(List<Double> values) {
            addCriterion("start_location_lng not in", values, "startLocationLng");
            return (Criteria) this;
        }

        public Criteria andStartLocationLngBetween(Double value1, Double value2) {
            addCriterion("start_location_lng between", value1, value2, "startLocationLng");
            return (Criteria) this;
        }

        public Criteria andStartLocationLngNotBetween(Double value1, Double value2) {
            addCriterion("start_location_lng not between", value1, value2, "startLocationLng");
            return (Criteria) this;
        }

        public Criteria andEndLocationNameIsNull() {
            addCriterion("end_location_name is null");
            return (Criteria) this;
        }

        public Criteria andEndLocationNameIsNotNull() {
            addCriterion("end_location_name is not null");
            return (Criteria) this;
        }

        public Criteria andEndLocationNameEqualTo(String value) {
            addCriterion("end_location_name =", value, "endLocationName");
            return (Criteria) this;
        }

        public Criteria andEndLocationNameNotEqualTo(String value) {
            addCriterion("end_location_name <>", value, "endLocationName");
            return (Criteria) this;
        }

        public Criteria andEndLocationNameGreaterThan(String value) {
            addCriterion("end_location_name >", value, "endLocationName");
            return (Criteria) this;
        }

        public Criteria andEndLocationNameGreaterThanOrEqualTo(String value) {
            addCriterion("end_location_name >=", value, "endLocationName");
            return (Criteria) this;
        }

        public Criteria andEndLocationNameLessThan(String value) {
            addCriterion("end_location_name <", value, "endLocationName");
            return (Criteria) this;
        }

        public Criteria andEndLocationNameLessThanOrEqualTo(String value) {
            addCriterion("end_location_name <=", value, "endLocationName");
            return (Criteria) this;
        }

        public Criteria andEndLocationNameLike(String value) {
            addCriterion("end_location_name like", value, "endLocationName");
            return (Criteria) this;
        }

        public Criteria andEndLocationNameNotLike(String value) {
            addCriterion("end_location_name not like", value, "endLocationName");
            return (Criteria) this;
        }

        public Criteria andEndLocationNameIn(List<String> values) {
            addCriterion("end_location_name in", values, "endLocationName");
            return (Criteria) this;
        }

        public Criteria andEndLocationNameNotIn(List<String> values) {
            addCriterion("end_location_name not in", values, "endLocationName");
            return (Criteria) this;
        }

        public Criteria andEndLocationNameBetween(String value1, String value2) {
            addCriterion("end_location_name between", value1, value2, "endLocationName");
            return (Criteria) this;
        }

        public Criteria andEndLocationNameNotBetween(String value1, String value2) {
            addCriterion("end_location_name not between", value1, value2, "endLocationName");
            return (Criteria) this;
        }

        public Criteria andEndLocationLatIsNull() {
            addCriterion("end_location_lat is null");
            return (Criteria) this;
        }

        public Criteria andEndLocationLatIsNotNull() {
            addCriterion("end_location_lat is not null");
            return (Criteria) this;
        }

        public Criteria andEndLocationLatEqualTo(Double value) {
            addCriterion("end_location_lat =", value, "endLocationLat");
            return (Criteria) this;
        }

        public Criteria andEndLocationLatNotEqualTo(Double value) {
            addCriterion("end_location_lat <>", value, "endLocationLat");
            return (Criteria) this;
        }

        public Criteria andEndLocationLatGreaterThan(Double value) {
            addCriterion("end_location_lat >", value, "endLocationLat");
            return (Criteria) this;
        }

        public Criteria andEndLocationLatGreaterThanOrEqualTo(Double value) {
            addCriterion("end_location_lat >=", value, "endLocationLat");
            return (Criteria) this;
        }

        public Criteria andEndLocationLatLessThan(Double value) {
            addCriterion("end_location_lat <", value, "endLocationLat");
            return (Criteria) this;
        }

        public Criteria andEndLocationLatLessThanOrEqualTo(Double value) {
            addCriterion("end_location_lat <=", value, "endLocationLat");
            return (Criteria) this;
        }

        public Criteria andEndLocationLatIn(List<Double> values) {
            addCriterion("end_location_lat in", values, "endLocationLat");
            return (Criteria) this;
        }

        public Criteria andEndLocationLatNotIn(List<Double> values) {
            addCriterion("end_location_lat not in", values, "endLocationLat");
            return (Criteria) this;
        }

        public Criteria andEndLocationLatBetween(Double value1, Double value2) {
            addCriterion("end_location_lat between", value1, value2, "endLocationLat");
            return (Criteria) this;
        }

        public Criteria andEndLocationLatNotBetween(Double value1, Double value2) {
            addCriterion("end_location_lat not between", value1, value2, "endLocationLat");
            return (Criteria) this;
        }

        public Criteria andEndLocationLngIsNull() {
            addCriterion("end_location_lng is null");
            return (Criteria) this;
        }

        public Criteria andEndLocationLngIsNotNull() {
            addCriterion("end_location_lng is not null");
            return (Criteria) this;
        }

        public Criteria andEndLocationLngEqualTo(Double value) {
            addCriterion("end_location_lng =", value, "endLocationLng");
            return (Criteria) this;
        }

        public Criteria andEndLocationLngNotEqualTo(Double value) {
            addCriterion("end_location_lng <>", value, "endLocationLng");
            return (Criteria) this;
        }

        public Criteria andEndLocationLngGreaterThan(Double value) {
            addCriterion("end_location_lng >", value, "endLocationLng");
            return (Criteria) this;
        }

        public Criteria andEndLocationLngGreaterThanOrEqualTo(Double value) {
            addCriterion("end_location_lng >=", value, "endLocationLng");
            return (Criteria) this;
        }

        public Criteria andEndLocationLngLessThan(Double value) {
            addCriterion("end_location_lng <", value, "endLocationLng");
            return (Criteria) this;
        }

        public Criteria andEndLocationLngLessThanOrEqualTo(Double value) {
            addCriterion("end_location_lng <=", value, "endLocationLng");
            return (Criteria) this;
        }

        public Criteria andEndLocationLngIn(List<Double> values) {
            addCriterion("end_location_lng in", values, "endLocationLng");
            return (Criteria) this;
        }

        public Criteria andEndLocationLngNotIn(List<Double> values) {
            addCriterion("end_location_lng not in", values, "endLocationLng");
            return (Criteria) this;
        }

        public Criteria andEndLocationLngBetween(Double value1, Double value2) {
            addCriterion("end_location_lng between", value1, value2, "endLocationLng");
            return (Criteria) this;
        }

        public Criteria andEndLocationLngNotBetween(Double value1, Double value2) {
            addCriterion("end_location_lng not between", value1, value2, "endLocationLng");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("order_status is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("order_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(String value) {
            addCriterion("order_status =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(String value) {
            addCriterion("order_status <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(String value) {
            addCriterion("order_status >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(String value) {
            addCriterion("order_status >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(String value) {
            addCriterion("order_status <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(String value) {
            addCriterion("order_status <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLike(String value) {
            addCriterion("order_status like", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotLike(String value) {
            addCriterion("order_status not like", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<String> values) {
            addCriterion("order_status in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<String> values) {
            addCriterion("order_status not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(String value1, String value2) {
            addCriterion("order_status between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(String value1, String value2) {
            addCriterion("order_status not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_record
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_record
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}