package com.lantian.FindCar.dao;

import java.util.Date;

public class OrderRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.user_animate_id
     *
     * @mbggenerated
     */
    private Long userAnimateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.driver_animate_id
     *
     * @mbggenerated
     */
    private Long driverAnimateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.car_cate
     *
     * @mbggenerated
     */
    private String carCate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.start_location_name
     *
     * @mbggenerated
     */
    private String startLocationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.start_location_lat
     *
     * @mbggenerated
     */
    private Double startLocationLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.start_location_lng
     *
     * @mbggenerated
     */
    private Double startLocationLng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.end_location_name
     *
     * @mbggenerated
     */
    private String endLocationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.end_location_lat
     *
     * @mbggenerated
     */
    private Double endLocationLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.end_location_lng
     *
     * @mbggenerated
     */
    private Double endLocationLng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_status
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.id
     *
     * @return the value of order_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.id
     *
     * @param id the value for order_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.user_animate_id
     *
     * @return the value of order_record.user_animate_id
     *
     * @mbggenerated
     */
    public Long getUserAnimateId() {
        return userAnimateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.user_animate_id
     *
     * @param userAnimateId the value for order_record.user_animate_id
     *
     * @mbggenerated
     */
    public void setUserAnimateId(Long userAnimateId) {
        this.userAnimateId = userAnimateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.driver_animate_id
     *
     * @return the value of order_record.driver_animate_id
     *
     * @mbggenerated
     */
    public Long getDriverAnimateId() {
        return driverAnimateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.driver_animate_id
     *
     * @param driverAnimateId the value for order_record.driver_animate_id
     *
     * @mbggenerated
     */
    public void setDriverAnimateId(Long driverAnimateId) {
        this.driverAnimateId = driverAnimateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.create_time
     *
     * @return the value of order_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.create_time
     *
     * @param createTime the value for order_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.car_cate
     *
     * @return the value of order_record.car_cate
     *
     * @mbggenerated
     */
    public String getCarCate() {
        return carCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.car_cate
     *
     * @param carCate the value for order_record.car_cate
     *
     * @mbggenerated
     */
    public void setCarCate(String carCate) {
        this.carCate = carCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.start_location_name
     *
     * @return the value of order_record.start_location_name
     *
     * @mbggenerated
     */
    public String getStartLocationName() {
        return startLocationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.start_location_name
     *
     * @param startLocationName the value for order_record.start_location_name
     *
     * @mbggenerated
     */
    public void setStartLocationName(String startLocationName) {
        this.startLocationName = startLocationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.start_location_lat
     *
     * @return the value of order_record.start_location_lat
     *
     * @mbggenerated
     */
    public Double getStartLocationLat() {
        return startLocationLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.start_location_lat
     *
     * @param startLocationLat the value for order_record.start_location_lat
     *
     * @mbggenerated
     */
    public void setStartLocationLat(Double startLocationLat) {
        this.startLocationLat = startLocationLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.start_location_lng
     *
     * @return the value of order_record.start_location_lng
     *
     * @mbggenerated
     */
    public Double getStartLocationLng() {
        return startLocationLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.start_location_lng
     *
     * @param startLocationLng the value for order_record.start_location_lng
     *
     * @mbggenerated
     */
    public void setStartLocationLng(Double startLocationLng) {
        this.startLocationLng = startLocationLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.end_location_name
     *
     * @return the value of order_record.end_location_name
     *
     * @mbggenerated
     */
    public String getEndLocationName() {
        return endLocationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.end_location_name
     *
     * @param endLocationName the value for order_record.end_location_name
     *
     * @mbggenerated
     */
    public void setEndLocationName(String endLocationName) {
        this.endLocationName = endLocationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.end_location_lat
     *
     * @return the value of order_record.end_location_lat
     *
     * @mbggenerated
     */
    public Double getEndLocationLat() {
        return endLocationLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.end_location_lat
     *
     * @param endLocationLat the value for order_record.end_location_lat
     *
     * @mbggenerated
     */
    public void setEndLocationLat(Double endLocationLat) {
        this.endLocationLat = endLocationLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.end_location_lng
     *
     * @return the value of order_record.end_location_lng
     *
     * @mbggenerated
     */
    public Double getEndLocationLng() {
        return endLocationLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.end_location_lng
     *
     * @param endLocationLng the value for order_record.end_location_lng
     *
     * @mbggenerated
     */
    public void setEndLocationLng(Double endLocationLng) {
        this.endLocationLng = endLocationLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_status
     *
     * @return the value of order_record.order_status
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_status
     *
     * @param orderStatus the value for order_record.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }
}