package com.lantian.FindCar.dao;

import java.util.Date;

public class UserBaseInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_information.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_information.phoneNum
     *
     * @mbggenerated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_information.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_information.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_information.created_location
     *
     * @mbggenerated
     */
    private String createdLocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_information.id
     *
     * @return the value of user_base_information.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_information.id
     *
     * @param id the value for user_base_information.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_information.phoneNum
     *
     * @return the value of user_base_information.phoneNum
     *
     * @mbggenerated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_information.phoneNum
     *
     * @param phonenum the value for user_base_information.phoneNum
     *
     * @mbggenerated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_information.name
     *
     * @return the value of user_base_information.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_information.name
     *
     * @param name the value for user_base_information.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_information.created_time
     *
     * @return the value of user_base_information.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_information.created_time
     *
     * @param createdTime the value for user_base_information.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_information.created_location
     *
     * @return the value of user_base_information.created_location
     *
     * @mbggenerated
     */
    public String getCreatedLocation() {
        return createdLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_information.created_location
     *
     * @param createdLocation the value for user_base_information.created_location
     *
     * @mbggenerated
     */
    public void setCreatedLocation(String createdLocation) {
        this.createdLocation = createdLocation == null ? null : createdLocation.trim();
    }
}