package com.lantian.FindCar.mapper;

import com.lantian.FindCar.dao.ConfirmCode;
import com.lantian.FindCar.dao.ConfirmCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfirmCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_code
     *
     * @mbggenerated
     */
    int countByExample(ConfirmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_code
     *
     * @mbggenerated
     */
    int deleteByExample(ConfirmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_code
     *
     * @mbggenerated
     */
    int insert(ConfirmCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_code
     *
     * @mbggenerated
     */
    int insertSelective(ConfirmCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_code
     *
     * @mbggenerated
     */
    List<ConfirmCode> selectByExample(ConfirmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_code
     *
     * @mbggenerated
     */
    ConfirmCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_code
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ConfirmCode record, @Param("example") ConfirmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_code
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ConfirmCode record, @Param("example") ConfirmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfirmCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConfirmCode record);
}