package com.lantian.FindCar.mapper;

import com.lantian.FindCar.dao.DriverAnimateInformation;
import com.lantian.FindCar.dao.DriverAnimateInformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DriverAnimateInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_animate_information
     *
     * @mbggenerated
     */
    int countByExample(DriverAnimateInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_animate_information
     *
     * @mbggenerated
     */
    int deleteByExample(DriverAnimateInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_animate_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_animate_information
     *
     * @mbggenerated
     */
    int insert(DriverAnimateInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_animate_information
     *
     * @mbggenerated
     */
    int insertSelective(DriverAnimateInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_animate_information
     *
     * @mbggenerated
     */
    List<DriverAnimateInformation> selectByExample(DriverAnimateInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_animate_information
     *
     * @mbggenerated
     */
    DriverAnimateInformation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_animate_information
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DriverAnimateInformation record, @Param("example") DriverAnimateInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_animate_information
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DriverAnimateInformation record, @Param("example") DriverAnimateInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_animate_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DriverAnimateInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_animate_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DriverAnimateInformation record);
}