package com.lantian.FindCar.mapper;

import com.lantian.FindCar.dao.OrderRecord;
import com.lantian.FindCar.dao.OrderRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    int countByExample(OrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    int deleteByExample(OrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    int insert(OrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    int insertSelective(OrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    List<OrderRecord> selectByExample(OrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    OrderRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderRecord record, @Param("example") OrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderRecord record, @Param("example") OrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderRecord record);
}