package com.lantian.FindCar.mapper;

import com.lantian.FindCar.dao.UserBaseInformation;
import com.lantian.FindCar.dao.UserBaseInformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBaseInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_information
     *
     * @mbggenerated
     */
    int countByExample(UserBaseInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_information
     *
     * @mbggenerated
     */
    int deleteByExample(UserBaseInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_information
     *
     * @mbggenerated
     */
    int insert(UserBaseInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_information
     *
     * @mbggenerated
     */
    int insertSelective(UserBaseInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_information
     *
     * @mbggenerated
     */
    List<UserBaseInformation> selectByExample(UserBaseInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_information
     *
     * @mbggenerated
     */
    UserBaseInformation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_information
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserBaseInformation record, @Param("example") UserBaseInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_information
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserBaseInformation record, @Param("example") UserBaseInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserBaseInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserBaseInformation record);
}